Repository clue/clue.engineering, pull requests merged in 2020-10, with the labels that each got.

#66 Reorder support page, new consulting and coaching packages and pricing
  www/src/landing-page.css
  www/support.html
Labels: new feature

#67 Add consulting topics with short descriptions
  www/src/landing-page.css
  www/support.html
Labels: new feature

#68 Add GitHub workflow to show diff between HTML pages on push/PRs
  .github/workflows/diff.yml
Labels: new feature

#69 Use default layout for all page instead of using duplicate HTML
  www/_layouts/default.html
  www/_layouts/post.twig
  www/contact.html
  www/index.html.twig
Labels: new feature

#70 Include Atom feed in all pages, i.e. including blog posts
  .github/workflows/diff.yml
  www/_layouts/default.html
Labels: new feature

#73 Fix "Email us" in blog posts with correct link
  www/_layouts/post.twig
Labels: bug

#74 Add footer section for all pages
  www/_layouts/default.html
  www/index.html.twig
  www/src/landing-page.css
Labels: new feature

#76 Minor text improvements
  www/_layouts/default.html
  www/support.html
Labels: bug, new feature

#75 Add two-column layout for topic list on medium-sized display (tablets)
  www/src/landing-page.css
Labels: new feature

#77 Remove border-left of first pricing package on support page
  www/src/landing-page.css
Labels: new feature

#78 Improve navigation, highlight "Get Support" link (CTA)
  www/_layouts/default.html
  www/src/landing-page.css
Labels: new feature

#81 Fix installation on Composer 2 by replacing conflicting package
  composer.json
  composer.lock
Labels: maintenance

#80 Improve share section texts
  www/_layouts/post.twig
  www/blog.html.twig
Labels: new feature

#79 Unify building links to blog posts and remove unneeded legacy IDs
  www/_posts/2018-12-19 introducing-reactphp-ssh-proxy.md
  www/_posts/2019-01-01 2018-in-review.md
  www/_posts/2019-01-07 introducing-tls-1-3-for-reactphp.md
  www/_posts/2019-01-14 introducing-reactphp-child-process.md
  www/_posts/2019-03-11 introducing-reactphp-redis.md
  www/_posts/2019-05-14 introducing-reactphp-sqlite.md
  www/_posts/2019-07-04 introducing-reactphp-cache.md
  www/_posts/2019-07-11 announcing-reactphp-lts.md
  www/blog.html.twig
  www/index.html.twig
  www/posts.atom.twig
Labels: maintenance

#82 Blog post SOAP v2.0.0 release
  www/_posts/2018-11-07 introducing-reactphp-soap.md
  www/_posts/2020-10-28 announcing-reactphp-soap-2.md
  www/src/2020-soap-2.png
Labels: new feature
